baseURL = "https://jgabrielfreitas.github.io/"
languageCode = "en-us"
title = "JGabrielFreitas"
theme = "strata"
disqusShortname = "jgabrielfreitas"
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "João Freitas"
	description = "a static site with my photos"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "profile_photo.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**João Freitas**,<br> photography and developer.<br>hero of Hyrule."
		bg = "bg.jpg"
		# The icons will be shown if you enter your username
		twitter = "jgabrielfreitas"
		github = "jgabrielfreitas"

		copyright = [
			"&copy; JGabrielFreitas",
			"more: [instagram](https://www.instagram.com/jgabrielfreitas/)"
		]


	[params.about]
		hide  = false
		title = "about me"
		content = "a nerd who like to take photos and write a lot of code.<br>I also saved Hyrule a few times."


	[params.portfolio]
		hide  = false
		title = "recent photos"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/beach.JPG"
			thumb = "thumbs/beach.JPG"
			title = "praia da reserva"
			description = "CABO FRIO • RJ"

		[[params.portfolio.gallery]]
			image = "fulls/garrafas.jpg"
			thumb = "thumbs/garrafas.jpg"
			title = "garrafas"
			description = "ANTIGA FÁBRICA DE BHERING • RJ"

		[[params.portfolio.gallery]]
			image = "fulls/pearl_jam.JPG"
			thumb = "thumbs/pearl_jam.JPG"
			title = "pearl jam"
			description = "MARACANÃ • RJ"

		[[params.portfolio.gallery]]
			image = "fulls/paqueta.jpg"
			thumb = "thumbs/paqueta.jpg"
			title = "bicicletas"
			description = "PAQUETÁ • RJ"

		[[params.portfolio.gallery]]
			image = "fulls/red_hot.jpg"
			thumb = "thumbs/red_hot.jpg"
			title = "cover"
			description = "CALABOUÇO HEAVY METAL BAR • RJ"

		[[params.portfolio.gallery]]
			image = "fulls/biblioteca.jpg"
			thumb = "thumbs/biblioteca.jpg"
			title = "livros"
			description = "LIVRARIA DA TRAVESSA • RJ"

		[[params.portfolio.gallery]]
			image = "fulls/neon.jpg"
			thumb = "thumbs/neon.jpg"
			title = "neon"
			description = "HAMBURGUERIA DA ALFÂNDEGA • RJ"


	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
#[[menu.main]]
#	name = "Home"
#	url  = "/"
#	weight = 10